[build]
  command = "npm install && npm run build && npm run client-install && npm run client-build"
  functions = "functions"

[[redirects]]
  from = "/[news|team|praxis|fragen|tiergestuetzte_therapie|anfahrt|kontakt|impressum|datenschutz]"
  to = "/"
  status = 200
